"""empty message

Revision ID: 5f98ea41a804
Revises: 8f5d760d7804
Create Date: 2021-11-02 03:14:18.849669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f98ea41a804'
down_revision = '8f5d760d7804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuentas', sa.Column('beneficio_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuentas', 'beneficio_total')
    # ### end Alembic commands ###
